name: Sync from mozilla-central

on:
  schedule:
    # every day at 5:30 and 17:30 UTC
    - cron: '30 5,17 * * *'
  workflow_dispatch:

jobs:
  sync:
    name: Sync
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/cache@v4
        with:
          path: _cache/upstream
          key: upstream
      - name: Run synchronization script
        run:  ./.github/sync/sync.sh _filtered
      - name: Pushing new `main`
        run: git push origin main
